# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
