# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=100),
        ),
    ]
