# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190729_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
