# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="Hey there.I'm using Instagram"),
        ),
    ]
