# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="Hey there!I'm using Instagram"),
        ),
    ]
